### ISSUE TITLE
Main todo list

### ISSUE THREAD

**Issue by tima101** [async-labs/saas#14]
@klyburke @delgermurun  Below is the list of improvements I had in mind, if you have time, please suggest more.

- [x] make main layout, settings, billing similar to Async so it is easier to maintain
- [x] UX/UI improvements to Posts (similar to what we did for Async)
- [x] toggle for dark/light theme
- [x] AWS Lambda and SES: email notification for new Post (new or existing Discussion)
- [x] limit number of team members inside team for free plan to 2, show notifier that asks to become a paid customer when team leader adds a third member
- [x] websokets see #23
- [x] passwordless authentication in addition to Google OAuth
- [ ] write an introduction article at: https://async-await.com/articles

<details>
      <summary>Click to see <b>Hill for issue #14</b></summary>
      <div><img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/14.png" alt="Single issue hill" class="s3-image"/></div></details>
      <details><summary>Click to see <b>Hill for all issues </b></summary><div>
      <img src="https://async-github-hills.s3.amazonaws.com/async-labs-saas/all-issue-hill.png" alt="All issue hill" class="s3-image"/></div></details>
      
created by [Async](https://async-await.com/

**Comment by klyburke** [comment]
@tima101  I'll add suggestions here as I think about them:
 - toggle for dark/light theme
